variables:
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/') }}:
    branchName: $[ replace(variables['Build.SourceBranch'], 'refs/heads/', '') ]
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}:
    branchName: $[ replace(variables['System.PullRequest.SourceBranch'], 'refs/heads/', '') ]
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  isDevelop: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]

trigger:
  - main
  - feat/*
  - develop

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    persistCredentials: true

  - script: |

      # Install urlencode function to encode reserved characters in passwords
      sudo apt-get install gridsite-clients

      # Create local mirror of Azure DevOps repository
      git clone --mirror https://$(System.AccessToken)@dev.azure.com/worldfoodprogramme/Design%20System/_git/bridge repo-mirror


      # Sync AWS CodeCommit repository
      cd repo-mirror
      git push --mirror https://${AWS_GIT_USERNAME}:$(urlencode ${AWS_GIT_PASSWORD})@${AWS_REPO_URL}

    displayName: "Sync repository with AWS CodeCommit"
    env:
      AZURE_REPO_URL: $(AZURE_REPO_URL)
      AZURE_GIT_USERNAME: $(AZURE_GIT_USERNAME)
      AZURE_GIT_PASSWORD: $(AZURE_GIT_PASSWORD)
      AWS_REPO_URL: $(AWS_REPO_URL)
      AWS_GIT_USERNAME: $(AWS_GIT_USERNAME)
      AWS_GIT_PASSWORD: $(AWS_GIT_PASSWORD)

  - script: |
      git config --global user.name "Azure Devops Pipeline"
      git config --global user.email "roberg.guehne@wfp.org"
    displayName: Git config user

  - task: CmdLine@2
    displayName: Checkout $(branchName) Original $(Build.SourceBranch)
    inputs:
      script: |
        git fetch --all
        git checkout $(branchName)
  - task: NodeTool@0
    inputs:
      versionSpec: "18.x"
    displayName: "Install Node.js"

  - task: DownloadSecureFile@1
    name: npmrcFile
    displayName: "Download npmrc certificate"
    inputs:
      secureFile: "npmrc"
  - task: CmdLine@2
    inputs:
      script: cp $(npmrcFile.secureFilePath) ./.npmrc

  - script: |
      npm run lerna:versionNoPush
      git push --follow-tags origin HEAD:$(branchName)
    displayName: "npm run lerna:version"
    condition: or( eq(variables.isMain, 'true'), eq(variables.isDevelop, 'true') )

  - bash: echo "##vso[task.setvariable variable=yarnCacheDir;]$(yarn cache dir)"
    displayName: Set yarn cache dir variable

  - script: |
      npmVersionString=$(node -p "require('./lerna.json').version") 
      echo "##vso[build.updatebuildnumber]$npmVersionString"
    displayName: "set build number"
  - task: CmdLine@2
    inputs:
      script: |
        cp $(npmrcFile.secureFilePath) .npmrc
        cp $(npmrcFile.secureFilePath) ./packages/helpers/.npmrc
        ls -a
        cat .npmrc
  - task: Cache@2
    inputs:
      key: '"yarn" | "$(Agent.OS)" | yarn.lock'
      restoreKeys: |
        yarn | "$(Agent.OS)"
        yarn
      path: $(yarnCacheDir)
    displayName: Cache Yarn packages

  - script: |
      yarn install --frozen-lockfile
    displayName: "yarn install"

  - script: |
      yarn build
    displayName: "yarn build"

  - script: |
      npm run lerna:publishFromPackage
    displayName: "lerna publish"
    condition: eq(variables.isMain, 'true')

  - script: |
      npm run lerna:publishFromPackageAlpha
    displayName: "lerna publish alpha (Develop)"
    condition: eq(variables.isDevelop, 'true')
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: "./packages/react"
      artifact: "uncore-react"
      publishLocation: "pipeline"
